export const PORTFOLIO_ITEMS = [
  {
    id: 1,
    title: "나따오비까",
    subtitle: "나따오비까 팝업스토어 기획 및 운영",
    createdAt: "2025-02-28",
    partner: "나따오비까",
    imageSrc: "/sections/portfolio/nattaovie-starfield.jpg",
    imageAlt: "나따오비까 포트폴리오",
  },
  {
    id: 2,
    title: "마법의딸기",
    subtitle: "마법의딸기 전시 기획 및 운영",
    createdAt: "2023-10-20",
    partner: "마법의딸기",
    imageSrc: "/sections/portfolio/magic-strawberry-exhibition.jpg",
    imageAlt: "마법의딸기 포트폴리오",
  },
  {
    id: 3,
    title: "농심 빵부장",
    subtitle: "농심 빵부장 프로모션 진행",
    createdAt: "2024-09-07",
    partner: "농심",
    imageSrc: "/sections/portfolio/nongshim-mascot-event.jpg",
    imageAlt: "떡볶이먹고 포트폴리오",
  },
  {
    id: 4,
    title: "코코하 롯데 본점",
    subtitle: "코코하 팝업스토어 기획 및 운영",
    createdAt: "2025-02-16",
    partner: "코코하",
    imageSrc: "/sections/portfolio/kokohaa-popup-store.jpg",
    imageAlt: "피원파트너스 포트폴리오",
  },
  {
    id: 5,
    title: "(주)이안스푸드글로벌",
    subtitle: "삼열이네 전시 기획 및 운영",
    createdAt: "2024-10-03",
    partner: "(주)이안스푸드글로벌",
    imageSrc: "/sections/portfolio/sam-yeols.jpeg",
    imageAlt: "삼열이네포트폴리오",
  },
  {
    id: 6,
    title: "서울 스트로베리 페스타",
    subtitle: "서스페SETEC 전시 주최 기획 및 운영",
    createdAt: "2024-01-19",
    partner: "서울스트로베리페스타",
    imageSrc: "/sections/portfolio/seoul-strawberry-festa.png",
    imageAlt: "서울스트로베리페스타 포트폴리오",
  },
  {
    id: 7,
    title: "열혈사제2",
    subtitle: "열혈사제2 골목팝업 기획 및 운영",
    createdAt: "2024-12-13",
    partner: "길스토리IP",
    imageSrc: "/sections/why-kerberos/brand-connection.png",
    imageAlt: "열혈사제2 포트폴리오",
  },
  // {
  //   id: ,
  //   title: "",
  //   subtitle: "",
  //   createdAt: "",
  //   partner: "",
  //   imageSrc: "/sections/portfolio/jpg",
  //   imageAlt: "포트폴리오",
  // },
];
