export const PORTFOLIO_ITEMS = [
  {
    id: 1,
    title: "나따오비까 스타필드",
    subtitle: "나따오비까 스타필드 팝업스토어 운영",
    createdAt: "2025-01-01",
    partner: "나따오비까",
    imageSrc: "/sections/portfolio/nattaovie-starfield.jpg",
    imageAlt: "스타필드 포트폴리오",
  },
  {
    id: 2,
    title: "마법의 딸기",
    subtitle: "마법의 딸기 전시 기획",
    createdAt: "2025-01-01",
    partner: "마법의 딸기",
    imageSrc: "/sections/portfolio/magic-strawberry-exhibition.jpg",
    imageAlt: "마법의 딸기 포트폴리오",
  },
  {
    id: 3,
    title: "농심 빵부장",
    subtitle: "농심 빵부장 프로모션 진행",
    createdAt: "2025-01-01",
    partner: "농심",
    imageSrc: "/sections/portfolio/nongshim-mascot-event.jpg",
    imageAlt: "떡볶이먹고 포트폴리오",
  },
  {
    id: 4,
    title: "코코하 롯데 본점",
    subtitle: "코코하 팝업스토어 기획 및 운영",
    createdAt: "2025-01-01",
    partner: "코코하",
    imageSrc: "/sections/portfolio/kokohaa-popup-store.jpg",
    imageAlt: "피원파트너스 포트폴리오",
  },
  {
    id: 5,
    title: "더블스플랫폼",
    subtitle: "나따오비까 스타필드 팝업스토어 운영",
    createdAt: "2025-01-01",
    partner: "나따오비까",
    imageSrc: "/sections/portfolio/magic-strawberry-exhibition.jpg",
    imageAlt: "더블스플랫폼 포트폴리오",
  },
];
